DjangoPubg/urls.py
from django.contrib import admin
from django.urls import path, include
from pro import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('question/', include("question.urls")),
    path('gamer/', include("gamer.urls")),
    path('common/', include("common.urls")),
    path('pro/', include("pro.urls")),
    path('rank/', include("rank.urls")),
    path('', views.home, name='home'),  # '/' 에 해당되는 path
]

pro/urls.py
# apps/urls.py

from django.urls import path
from pro import views

app_name = "pro"

urlpatterns = [
    path('', views.index, name="index"),
    path('match/<str:match_id>/', views.detail, name='detail'),
    path('readCsv/', views.csvRead, name='match_data_read'),


]

pro/models.py
from django.db import models

# Create your models here.
class PgcList(models.Model):
    """
        match_id            매치 아이디
        tournament_type     대회 종류
        create_date         생성 시간
    """

    match_id         = models.CharField(max_length=100)
    tournament_type  = models.CharField(max_length=50)
    create_date      = models.CharField(max_length=50)

    def __str__(self):
        return self.tournament_type + ",", self.create_date + ",", self.match_id

class MatchData(models.Model):
    """
        match_id            매치 아이디
        created_at          게임 생성시간
        user_name           유저명
        kill                킬수
        headkill            헤드샷 킬수
        longestkill         킬 최대거리
        loadkill            로드킬
        teamkill            팀킬
        assist              도움 횟수
        damagedealt         총 입힌 데미지
        damagetaken         총 입은 데미지
        dbno                부활 횟수
        revive              부활 시킨 횟수
        walkdistance        걸은 거리
        ridedistance        차량 이동 거리
        swimdistance        수영 이동 거리
        distance            총 이동 거리
        boost               부스트 아이탬 사용 횟수
        heal                체력 회복 아이탬 사용 횟수
        deathtype           죽음 종류
        acquired            무기 습득 횟수
        team_member         팀원
        team_name           팀명
        team_kill           팀 총 킬수
        team_assist         팀 총 어시스트
        team_distance       팀 평균 이동 거리
        team_damagedealt    팀 총 가한 데미지
        team_damagetaken    팀 총 입은 데미지
        team_timesurvived   팀 평균 생존 시간
        timesurvived        생존 시간
        ranking             등수
        vehicle_destroys    차량 파괴 횟수
        map_name            맵이름
        game_duration       게임 지속 시간
    """

    match_id            = models.CharField(max_length=100)
    created_at          = models.CharField(max_length=50)
    user_name           = models.CharField(max_length=50)
    kill                = models.IntegerField()
    headkill            = models.IntegerField()
    longestkill         = models.FloatField()
    loadkill            = models.IntegerField()
    teamkill            = models.IntegerField()
    assist              = models.IntegerField()
    damagedealt         = models.FloatField()
    damagetaken         = models.FloatField()
    dbno                = models.IntegerField()
    revive              = models.IntegerField()
    walkdistance        = models.FloatField()
    ridedistance        = models.FloatField()
    swimdistance        = models.FloatField()
    distance            = models.FloatField()
    boost               = models.IntegerField()
    heal                = models.IntegerField()
    deathtype           = models.CharField(max_length=50)
    acquired            = models.IntegerField()
    team_member         = models.CharField(max_length=100)
    team_name           = models.CharField(max_length=50)
    team_kill           = models.IntegerField()
    team_assist         = models.IntegerField()
    team_distance       = models.FloatField()
    team_damagedealt    = models.FloatField()
    team_damagetaken    = models.FloatField()
    team_timesurvived   = models.FloatField()
    timesurvived        = models.FloatField()
    ranking             = models.IntegerField()
    vehicle_destroys    = models.IntegerField()
    map_name            = models.CharField(max_length=50)
    game_duration       = models.FloatField()
    # CSV파일에 존재하는 칼럼이지만, 백엔드에서 사용하지 않을것 같은데이터.. (만약 사용하게 될 수 있으니 작성)
    # kill_place, kill_streaks, player_id, telemetry_link, team_roster_id
    # player_id의 정보다 telemetry_link를 활용해서 매치 내에 자세한 정보를 추출 가능



class Video(models.Model):
    caption         = models.CharField(max_length=100)
    video           = models.FileField(upload_to="video/%y")
    thumb           = models.FileField(upload_to="thumb/%y", blank=True)
    def __str__(self):
        return self.caption

pro/forms.py
from django import forms
from pro.models import MatchData, PgcList


class MatchForm(forms.ModelForm):
    class Meta:
        model = PgcList  # 사용할 모델
        fields = ['create_date', 'tournament_type', 'create_date']
        labels = {
            'match_id': '매치 아이디',
            'tournament_type': '대회 종류',
            'create_date': '게임 생성시간',
        }

pro/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.http import HttpResponse
from pro.models import PgcList, MatchData, Video
from django.core.paginator import Paginator     # 페이징을 위한 라이브러리
import csv

''' 초기 화면 설정 (제일 첫 화면) '''
def home(request):
    return render(request, 'main.html')

''' 페이지의 첫 화면 '''
def index(request):
    page = request.GET.get('page', '1')  # 페이지
    match_list = PgcList.objects.order_by('-create_date')     # 앞에 - 가 붙으면 내림 차순
    paginator = Paginator(match_list, 20)  # 페이지당 20개 씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'PgcList' : page_obj}
    return render(request, 'pro/home.html', context)


""" 저장된 csv 파일 불러오기 """
def csvRead(request):
    PgcList.objects.all().delete()

    path = "C:/Users/HC/PycharmProjects/pubgProject/MatchList/datas/pgc/PGC_MATCH.csv"
    file = open(path)
    reader = csv.reader(file)
    print(reader)     # csv파일을 성공적으로 불러오는지 확인.
    list = []
    for count, row in enumerate(reader):
        if count == 0:      # 칼럼값 제외
            continue
        list.append(PgcList(tournament_type = row[0],
                            match_id = row[1],
                            create_date = row[2]))
    PgcList.objects.bulk_create(list)     # 리스트를 한번에 입력

    MatchData.objects.all().delete()
    path2 = "C:/Users/HC/PycharmProjects/pubgProject/MatchList/datas/pgc/MATCH_ALL_STAT.csv"
    file2 = open(path2)
    reader2 = csv.reader(file2)
    print(reader2)
    list2 = []
    for count, row in enumerate(reader2):
        if count == 0:
            continue
        list2.append(MatchData(
        match_id       = row[25]     ,#매치 아이디
        created_at     = row[26]     ,#게임 생성시간
        user_name      = row[11]     ,#유저명
        kill           = row[9]      ,#킬수
        headkill       = row[5]      ,#헤드샷 킬수
        longestkill    = round(float(row[10]),2)    ,#킬 최대거리
        loadkill       = row[15]     ,#로드킬
        teamkill       = row[17]     ,#팀킬
        assist         = row[1]      ,#도움 횟수
        damagedealt    = round(float(row[3]),2)      ,#총 입힌 데미지
        damagetaken    = round(float(row[23]),2)    ,#총 입은 데미지
        dbno           = row[0]      ,#부활 횟수
        revive         = row[13]     ,#부활 시킨 횟수
        walkdistance   = row[20]     ,#걸은 거리
        ridedistance   = row[14]     ,#차량 이동 거리
        swimdistance   = row[16]     ,#수영 이동 거리
        distance       = round(float(row[20])+float(row[14])+float(row[16]),2)    ,#총 이동 거리
        boost          = row[2]      ,#부스트 아이탬 사용 횟수
        heal           = row[6]      ,#체력 회복 아이탬 사용 횟수
        deathtype      = row[4]      ,#죽음 종류
        acquired       = row[21]     ,#무기 습득 횟수
        team_member    = row[31]     ,#팀원
        team_name      = row[24]     ,#팀이름
        team_kill      = row[33]     ,#팀 총 킬수
        team_assist    = row[34]     ,#팀 총 어시스트
        team_distance  = row[35]     ,#팀 평균 이동 거리
        team_damagedealt  = round(float(row[36]),2)  ,#팀 총 가한 데미지
        team_damagetaken  = round(float(row[37]),2)  ,#팀 총 입은 데미지
        team_timesurvived = row[38]  ,#팀 평균 생존 시간
        timesurvived      = row[18]  ,#생존 시간
        ranking           = row[22]  ,#등수
        vehicle_destroys  = row[19]  ,#차량 파괴 횟수
        map_name          = row[27]  ,#맵이름
        game_duration     = row[28]  ,#게임 지속 시간
        ))
    MatchData.objects.bulk_create(list2)  # 리스트를 한번에 입력

    return redirect('/pro/')


def detail(request, match_id):
    match_data = MatchData.objects.filter(match_id=match_id)
    video_path = "videos/pgc/" + match_id + ".html"
    context = {'match_data': match_data, "video" : video_path }
    return render(request, 'pro/pro_detail.html', context)



templates/pro/home.html
{% extends 'base.html' %}
{% load pgc_filter %}
{% block content %}


<div class="container my-3">

    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th><span data-tooltip-text="국가-대회이름,대회종류">대회종류</th>
            <th style="width:50%"><span data-tooltip-text="경기에 대한 고유번호">매치ID</th>
            <th>생성시간</th>
        </tr>
        </thead>
        <tbody>
        {% if PgcList %}
        {% for match in PgcList %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ PgcList.paginator.count|sub:PgcList.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                {% if 'pgcgf' in match.tournament_type%}
                    <span data-tooltip-text="Grand_Final : 그랜드 파이널(4일)">
                {% elif 'pgcgs' in match.tournament_type and 'pgcgsb' not in match.tournament_type %}
                    <span data-tooltip-text="Grand Survival : 그랜드 서바이벌(1일)">
                {% elif 'pgclbp' in match.tournament_type %}
                    <span data-tooltip-text="Losers Braket : 패자 브래킷(4일)">
                {% elif 'pgcwb' in match.tournament_type %}
                    <span data-tooltip-text="Winners Braket : 승자 브래킷(2일)">
                {% elif 'pgcgsb' in match.tournament_type %}
                    <span data-tooltip-text="Group Stage : 그룹 스테이지 (6일)">
                {% elif 'pgcws' in match.tournament_type %}
                    <span data-tooltip-text="Weekly Survival : 위클리 서바이벌 (3일)">
                {% elif 'pgcwf' in match.tournament_type %}
                    <span data-tooltip-text="Weekly Final : 위클리 파이널 (2일)">
                {% elif 'pgcbm' in match.tournament_type %}
                    <span data-tooltip-text="Bottom 16 : 하위 16개 팀의 경기 (2일)">
                {% elif 'pgcrd' in match.tournament_type %}
                    <span data-tooltip-text="Rank Decision : 순위 결정전 (3일)">
                {% else %}
                {% endif %}

                {{ match.tournament_type }}
            </td>
            <td>
                <a href="{% url 'pro:detail' match.match_id %}">{{ match.match_id }}</a>
            </td>
            <td>{{ match.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">매치 정보를 불러오지 못했습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if PgcList.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ PgcList.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in PgcList.paginator.page_range %}
        {% if page_number >= PgcList.number|add:-5 and page_number <= PgcList.number|add:5 %}
        {% if page_number == PgcList.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if PgcList.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ PgcList.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
   <a href = "{% url 'pro:match_data_read' %}" class="btn btn-primary">정보 업데이트</a>

</div>


{% endblock %}





templates/pro/pro_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <!-- 비디오 관련 (html파일을 로드 시켜 표현) -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">
    //<![CDATA[
    $(function(){
        $("#result").load("{% static video %}");
    });
    //]]>
    </script>

    <div id="result"></div>

    <table font-size:2px;>
        <thead>
        <tr>
            <th nowrap class="table-title">팀명</th>
            <th nowrap class="table-title">아이디</th>
            <th nowrap class="table-title">킬</th>
            <th nowrap class="table-title">헤드샷</th>
            <th nowrap class="table-title">로드킬</th>
            <th nowrap class="table-title">팀킬</th>
            <th nowrap class="table-title">최장거리 킬</th>
            <th nowrap class="table-title">어시스트</th>
            <th nowrap class="table-title">입힌<br>데미지</th>
            <th nowrap class="table-title">받은<br>데미지</th>
            <th nowrap class="table-title"><span data-tooltip-text="Down But No Out의 약자">DBNO</th>  <!-- (기절 했지만 부활 횟수) 이후 툴팁 같은 기능으로 추가설명-->
            <th nowrap class="table-title">살려준<br>횟수</th>
            <th nowrap class="table-title">죽음<br>종류</th>
            <!-- 생존 관련 -->
            <th nowrap class="table-title">생존시간</th>
            <th nowrap class="table-title">이동거리</th>
            <th nowrap class="table-title">회복</th>
            <th nowrap class="table-title">부스트</th>
            <th nowrap class="table-title">무기<br>획득</th>
            <th nowrap class="table-title">순위</th>
        </tr>
        </thead>
        <tbody>
        {% if match_data %}
        {% for match in match_data %}
        <tr class="text-center">
            <td nowrap> {{match.team_name}} </td>
            <td nowrap> {{match.user_name}} </td>
            <td nowrap> {{match.kill}}킬 </td>
            <td nowrap> {{match.headkill}}킬 </td>
            <td nowrap> {{match.loadkill}}킬 </td>
            <td nowrap> {{match.teamkill}}킬 </td>
            <td nowrap> {{match.longestkill}}(M) </td>
            <td nowrap> {{match.assist}}회 </td>
            <td nowrap> {{match.damagedealt}} </td>
            <td nowrap> {{match.damagetaken}} </td>
            <td nowrap> {{match.dbno}}회 </td>
            <td nowrap> {{match.revive}}회 </td>
            <td nowrap> {{match.deathtype}} </td>
            <!-- 생 관련 -->
            <td nowrap> {{match.timesurvived}} </td>
            <td nowrap> {{match.distance}}(M) </td>
            <td nowrap> {{match.heal}}회 </td>
            <td nowrap> {{match.boost}}회 </td>
            <td nowrap> {{match.acquired}}회 </td>
            <td nowrap> {{match.ranking}}위 </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="10">API 오류로 데이터를 불러오지 못했습니다. </td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href = "{% url 'pro:index' %}" class="btn btn-primary">초기화면</a>
</script>
{% endblock %}