DjangoPubg/urls.py
from django.contrib import admin
from django.urls import path, include
from pro import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('question/', include("question.urls")),
    path('gamer/', include("gamer.urls")),
    path('common/', include("common.urls")),
    path('pro/', include("pro.urls")),
    path('rank/', include("rank.urls")),
    path('', views.home, name='home'),  # '/' 에 해당되는 path
]

gamer/urls.py
from django.urls import path

from gamer import views

app_name = "gamer"

urlpatterns = [
    path('', views.index, name="index"),
    path('csv_read/', views.csvRead, name='alldata_read'),
    path('<str:match_id>/', views.detail, name='detail'),
]

pro/urls.py
# apps/urls.py

from django.urls import path
from pro import views

app_name = "pro"

urlpatterns = [
    path('', views.index, name="index"),
    path('match/<str:match_id>/', views.detail, name='detail'),
    path('readCsv/', views.csvRead, name='match_data_read'),


]

question/urls.py
from django.urls import path

from question import views

app_name = "question"

urlpatterns = [
    path('', views.index, name='index'),      # config/urls 에서 작성한 경로 + 해당 파일에서 작성한 경로 ("question/" + "")
    path("<int:question_id>/", views.detail, name='detail'),
    path("answer/create/<int:question_id>/", views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

gamer/models.py
from django.db import models
from django.utils import timezone

# https://wikidocs.net/71306

class Matchlist(models.Model):
    user_name        = models.CharField(max_length=50)
    create_date      = models.CharField(max_length=100)
    match_id         = models.CharField(max_length=100)

    def __str__(self):
        return self.user_name + ",", self.create_date + ",", self.match_id


class Matchdata(models.Model):
    # list            = models.ForeignKey(Matchlist, on_delete=models.CASCADE)
    user_id         = models.CharField(max_length=50, verbose_name = "유저명")
    kill            = models.IntegerField(verbose_name = "킬수")
    headkill        = models.IntegerField(verbose_name = "헤드샷 킬수")
    longestkill     = models.FloatField(verbose_name = "킬 최대거리")
    loadkill        = models.IntegerField(verbose_name = "로드킬")
    teamkill        = models.IntegerField(verbose_name = "팀킬")
    assist          = models.IntegerField(verbose_name = "도움 횟수")
    damagedealt     = models.FloatField(verbose_name = "총 입힌 데미지")
    damagetaken     = models.FloatField(verbose_name = "총 입은 데미지")
    dbno            = models.IntegerField(verbose_name = "부활횟수")
    revive          = models.IntegerField(verbose_name = "부활시킨 횟수")
    walkdistance    = models.FloatField(verbose_name = "걸은거리")
    ridedistance    = models.FloatField(verbose_name = "차량 이동거리")
    swimdistance    = models.FloatField(verbose_name = "수영 이동거리")
    distance        = models.FloatField(verbose_name = "총 이동거리")
    boost           = models.IntegerField(verbose_name = "부스트 아이탬 사용 횟수")
    heal            = models.IntegerField(verbose_name = "체력회복 아이탬 사용 횟수")
    deathtype       = models.CharField(max_length=50, verbose_name = "죽음종류")
    acquired        = models.IntegerField(verbose_name = "무기습득 횟수")
    teammate        = models.CharField(max_length=100, verbose_name = "팀원")
    timesurvived    = models.CharField(max_length=50, verbose_name = "생존시간")
    ranking         = models.IntegerField(verbose_name = "등수")
    map_name        = models.CharField(max_length=50, verbose_name = "맵이름")
    game_created    = models.CharField(max_length=100, verbose_name = "게임시작시간")
    game_mode       = models.CharField(max_length=50, verbose_name = "게임모드")
    game_duration   = models.CharField(max_length=50, verbose_name = "게임지속시간")

gamer/forms.py
from django import forms
from gamer.models import Matchdata, Matchlist


class MatchForm(forms.ModelForm):
    class Meta:
        model = Matchlist  # 사용할 모델
        fields = ['user_name', 'create_date', 'match_id']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'user_name': '아이디',
            'create_date': '게임 생성시간',
            'match_id': '매치 아이디',
        }

gamer/views.py

# Create your views here.
from django.shortcuts import render, redirect
import csv
from gamer.models import Matchlist, Matchdata
from django.core.paginator import Paginator     # 페이징을 위한 라이브러리
from MatchList.myGame_src.match_save import match_search_save

''' 초기 화면 설정 (제일 첫 화면) '''
def home(request):

    return render(request, 'main.html')


''' gamer 페이지의 첫 화면 '''
def index(request):
    page = request.GET.get('page', '1')  # 페이지
    match_list = Matchlist.objects.order_by('-create_date')     # 앞에 - 가 붙으면 내림 차순
    paginator = Paginator(match_list, 20)  # 페이지당 20개 씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'match_list' : page_obj}
    return render(request, 'gamer/home.html', context)


""" 저장된 csv 파일 불러오기 """
def csvRead(request):
    Matchlist.objects.all().delete()
    match_search_save(['Hwet_J', 'sickhu', '30XXDDD', 'hyeonji'])
    path = "C:/Users/HC/PycharmProjects/pubgProject/MatchList/datas/COMPETITIVE_MATCH.csv"
    file = open(path)
    reader = csv.reader(file)
    # print(reader)     # csv파일을 성공적으로 불러오는지 확인.
    list = []
    for count, row in enumerate(reader):
        if count == 0:      # 칼럼값 제외
            continue
        list.append(Matchlist(user_name = row[0],
                              create_date = row[1],
                              match_id = row[2]))
    Matchlist.objects.bulk_create(list)     # 리스트를 한번에 입력

    return redirect('/gamer/')

def detail(request, match_id):
    Matchdata.objects.all().delete()
    try:
        path = "C:/Users/HC/PycharmProjects/pubgProject/MatchList/datas/match_data/" + match_id +".csv"
        file = open(path)
        reader = csv.reader(file)
        # columns = [col for col in reader.fieldnames]
        # out = [row for row in reader]
        # print(out)
        # context = {'match_data': out}
        # return render(request, 'gamer/match_detail.html', context)

        list = []
        for count, row in enumerate(reader):
            if count == 0:  # 칼럼값 제외
                continue
            survived_time = str(int(row[20]) // 60) + "분 " + str(int(row[20]) % 60) + "초"
            duration_time = str(int(row[25]) // 60) + "분 " + str(int(row[25]) % 60) + "초"
            list.append(Matchdata(user_id=row[0],
                                  kill=row[1],
                                  headkill=row[2],
                                  longestkill=str(round(float(row[3]),2)),
                                  loadkill=row[4],
                                  teamkill=row[5],
                                  assist=row[6],
                                  damagedealt=str(round(float(row[7]),2)),
                                  damagetaken=str(round(float(row[8]),2)),
                                  dbno=row[9],
                                  revive=row[10],
                                  walkdistance=row[11],
                                  ridedistance=row[12],
                                  swimdistance=row[13],
                                  distance=str(round(float(row[14]),3)),
                                  boost=row[15],
                                  heal=row[16],
                                  deathtype=row[17],
                                  acquired=row[18],
                                  teammate=row[19],
                                  timesurvived=survived_time,
                                  ranking=row[21],
                                  map_name=row[22],
                                  game_created=row[23],
                                  game_mode=row[24],
                                  game_duration=duration_time,
                                  ))
        Matchdata.objects.bulk_create(list)
    except Exception as e:
        print(e)

    match_data = Matchdata.objects.order_by("teammate")
    # user_data = Matchdata.objects.filter("Hwet_J")
    context = {'match_data': match_data}
    return render(request, 'gamer/match_detail.html', context)



templates/gamer/home.html
{% extends 'base.html' %}
{% load match_filter %}
{% block content %}


<div class="container my-3">

    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">매치ID</th>
            <th>생성시간</th>
            <th>유저명</th>
        </tr>
        </thead>
        <tbody>
        {% if match_list %}
        {% for match in match_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ match_list.paginator.count|sub:match_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'gamer:detail' match.match_id%}">{{ match.match_id }}</a>
            </td>
            <td>{{ match.create_date }}</td>
            <td>{{ match.user_name }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if match_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ match_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in match_list.paginator.page_range %}
        {% if page_number >= match_list.number|add:-5 and page_number <= match_list.number|add:5 %}
        {% if page_number == match_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if match_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ match_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href = "{% url 'gamer:alldata_read' %}" class="btn btn-primary">정보 업데이트</a>
</div>

{% endblock %}






templates/gamer/match_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>아이디</th>
            <th>팀원</th>
            <th>킬</th>
            <th>헤드샷</th>
            <th>로드킬</th>
            <th>팀킬</th>
            <th>최장거리 킬</th>
            <th>어시스트</th>
            <th>입힌 데미지</th>
            <th>받은 데미지</th>
            <th>DBNO</th>  <!-- (기절 했지만 부활 횟수) 이후 툴팁 같은 기능으로 추가설명-->
            <th>살려준 횟수</th>
            <th>죽음 종류</th>
            <!-- 생존 관련 -->
            <th>생존 시간</th>
            <th>총 이동거리</th>
            <th>회복</th>
            <th>부스트</th>
            <th>무기 획득</th>
            <th>순위</th>
        </tr>
        </thead>
        <tbody>
        {% if match_data %}
        {% for match in match_data %}
        <tr class="text-center">
            <td> {{ match.user_id }} </td>
            <td> {{ match.teammate }} </td>
            <td> {{ match.kill }} </td>
            <td> {{ match.headkill }}</td>
            <td> {{ match.loadkill }}</td>
            <td> {{ match.teamkill }}</td>
            <td> {{ match.longestkill }} (M)</td>
            <td> {{ match.assist }}</td>
            <td> {{ match.damagedealt }}</td>
            <td> {{ match.damagetaken }}</td>
            <td> {{ match.dbno }}</td>
            <td> {{ match.revive }}</td>
            <td> {{ match.deathtype }}</td>
            <!-- 생손 관련 -->
            <td> {{ match.timesurvived }}</td>
            <td> {{ match.distance }} (KM)</td>
            <td> {{ match.heal }}</td>
            <td> {{ match.boost }}</td>
            <td> {{ match.acquired }}</td>
            <td> {{ match.ranking }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="10">API 오류로 데이터를 불러오지 못했습니다. </td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</script>
{% endblock %}

templates/gamer/match_list.html
{% extends 'base.html' %}
{% load match_filter %}
{% block content %}


<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호{{ match.user_name }}</th>
            <th style="width:50%">유저명</th>
            <th>생성시간</th>
            <th>매치ID</th>
        </tr>
        </thead>
        <tbody>
        {% if match_list %}
        {% for match in match_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ match_list.paginator.count|sub:match_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'gamer:detail' match.id %}">{{ match.match_id }}11</a>
            </td>
            <td>{{ match.create_date }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ match.user_name }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ match_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href = "{% url 'question:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>

{% endblock %}