DjangoPubg/urls.py
from django.contrib import admin
from django.urls import path, include
from pro import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('question/', include("question.urls")),
    path('gamer/', include("gamer.urls")),
    path('common/', include("common.urls")),
    path('pro/', include("pro.urls")),
    path('rank/', include("rank.urls")),
    path('', views.home, name='home'),  # '/' 에 해당되는 path
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

gamer/urls.py
from django.urls import path

from gamer import views

app_name = "gamer"

urlpatterns = [
    path('', views.index, name="index"),
    path('csv_read/', views.csvRead, name='alldata_read'),
    path('<str:match_id>/', views.detail, name='detail'),
]

pro/urls.py
# apps/urls.py

from django.urls import path
from pro import views

app_name = "pro"

urlpatterns = [
    path('', views.index, name="index"),
    path('match/<str:match_id>/', views.detail, name='detail'),
    path('readCsv/', views.csvRead, name='match_data_read'),


]

question/urls.py
from django.urls import path

from question import views

app_name = "question"

urlpatterns = [
    path('', views.index, name='index'),      # config/urls 에서 작성한 경로 + 해당 파일에서 작성한 경로 ("question/" + "")
    path("<int:question_id>/", views.detail, name='detail'),
    path("answer/create/<int:question_id>/", views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

rank/urls.py
# apps/urls.py

from django.urls import path
from rank import views

app_name = "rank"

urlpatterns = [
    path('', views.index, name="index"),
    path('read_data', views.readData, name="read_data"),
    path('pre_rank/', views.predict_rank, name="pre_rank"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- question CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- 테이블 CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'table.css' %}">
    <!-- 툴팁 CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'tooltip.css' %}">
    <!-- Video.js -->
    <link href="https://vjs.zencdn.net/7.20.3/video-js.css" rel="stylesheet" />
    <title>Hwet</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS(반응형 기능 적용 가능) -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://vjs.zencdn.net/7.20.3/video.min.js"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/main.html
{% extends 'base.html' %}
{% load pgc_filter %}
{% block content %}


<div class="container my-3">
        <h3>MAIN HOMEPAGE</h3>
        <a href="{% url 'pro:index' %}">PGC 기록</a><br><br>
        <a href="{% url 'gamer:index' %}">내 기록</a><br><br>
        <a href="{% url 'rank:index' %}">순위 예측하기</a><br><br>
        <a href="{% url 'question:index' %}">질문 게시판</a><br>
</div>


{% endblock %}





templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Hwet</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                     <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>